import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import TextInput from "@/components/TextInput";
import SubmitButton from "@/components/SubmitButton";
import ResponseDisplay from "@/components/ResponseDisplay";
import useApi from "@/hooks/useApi";
import Conversation from "@/components/Conversation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [messages, setMessages] = useState([
    {
      role: "system",
      content:
        "Hello, I'm Doggy your assistant to generate creative pet names.",
    },
  ]);
  const [inputValue, setInputValue] = useState("");
  const [submitValue, setSubmitValue] = useState("");
  const { data, error, loading } = useApi("/api/openai", "POST", {
    submitValue,
    setMessages,
  });

  // console.log(messages);

  const handleSubmit = () => {
    setMessages((messages) => [
      ...messages,
      { role: "user", content: inputValue },
    ]);
    setSubmitValue(
      JSON.stringify([...messages, { role: "user", content: inputValue }])
    );
    setInputValue("");
  };

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  return (
    <>
      <Head>
        <title>NextJS OpenAI Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1 className={inter.className}>NextJS OpenAI Boilerplate</h1>
        <Conversation messages={messages} />
        <ResponseDisplay data={data} error={error} loading={loading} />
        <TextInput value={inputValue} onChange={handleInputChange} />
        <SubmitButton onClick={handleSubmit} disabled={loading} />
      </main>
    </>
  );
}
